import json, pathlib, datetime

P = pathlib.Path("C:/Users/Wasch/carapace/Architecture/handoff/handoff.json")
h = json.loads(P.read_text(encoding="utf-8"))

h["last_updated"] = datetime.datetime.now(datetime.timezone.utc).isoformat()

h["orientation"] = (
    "Day 189, Saturday 2026-08-08, ~15:00 local. **V.3 — THE SCHOLASTICS AND THE GOD WITHOUT A "
    "FACE IS DRAFTED.** Book V is 3/11; the book is 35/67, 104,627 words.\n\n"
    "GAUGE FIRST, ALWAYS: `C:/Python314/python.exe tools/where_the_book_is.py` in "
    "`C:/Users/Wasch/truth-and-consequences`. All four carriers agree with disk as of this write.\n\n"
    "WHAT V.3 ACTUALLY DID, and the reason it is not the chapter the old brief described: "
    "`prose_beat_sweep --chapter V.3 --brief` came back with **V.2 at RANK 1 on two of the four "
    "beats** — `actus purus` -> V.2:255 at cos 0.649 (the highest score in the brief, and the "
    "paragraph that names `actus purus`), and *the popular religions re-added the face* -> V.2:268 "
    "at 0.576. A third item, *Aquinas and Augustine*, fell under the six-distinct-word floor and "
    "was not swept at all, because two proper nouns are a TOPIC and not a beat. **Three of four "
    "items were spent in the chapter drafted three hours earlier.** V.2's closing paragraphs were "
    "written as a handoff TO V.3 and what they did was DELIVER V.3. Grep then found the bigger "
    "spend the sweep could not: IV.8:70-90, 118-135 and 388-412 have already drafted the apophatic "
    "chapter in pieces, and V.1:110-135 ships the transmission audit.\n\n"
    "So the brief was REWRITTEN BEFORE DRAFTING, on the gauge rather than on a hunch, and the "
    "chapter was built on the one unspent item: **the identity claim — our Ground and theirs are "
    "the same object.** ★ V.1's transmission audit is what forces the method: those three men are "
    "ONE school in three languages (Plotinus -> Proclus -> Dionysius -> Latin -> Aquinas and "
    "Eckhart; the Baghdad translations into Maimonides' tradition), so convergence is unavailable "
    "and what is left is a **predicate audit under C27**. HOLDS on three (not a being among beings; "
    "no positive statement true; not an addressee). **FAILS on two, and the chapter picks**: (a) "
    "the Good — the convertibility of being and goodness makes their ground the foundation of an "
    "ethics and C6/C16/C24 forbid ours the same move, so Book VIII must earn its ethics from inside "
    "with no help from the floor; (b) creation vs the Focusing — a free act that could have been "
    "otherwise against something that is not an act and has no could-have-been-otherwise. Picked "
    "the Focusing, and the reason given is an internal inconsistency in THEIR account (free "
    "creation needs a chooser; a chooser is a position with an inside; the same books deny the "
    "object a position), not a preference.\n\n"
    "THE RESCUE CLAUSE WAS REFUSED WHERE IT STOOD: *it fails only on what it does, and it does "
    "nothing, so the divergence is narrow* is named on the page and killed — a ground that wills is "
    "a different object from a ground that cannot, so one account is wrong and it might be ours. "
    "The chapter names **contingency** as the deciding predicate, says no one in it can run that "
    "test, and calls the joint the weakest in the book.\n\n"
    "AUGUSTINE is in for the ROUTE, not the mention count: he reaches the ground by going inward, "
    "which is `02`'s method performed in 400 — **and he arrives at a personal Trinitarian God by "
    "our road.** Route converges, terminus does not. That is what stops the chapter being a "
    "roll-call of people who agree with us.\n\n"
    "ONE claim_sweep BREACH, MINE, FIXED: [TERM/fullness] at V.3:96 — I reached back for Book I's "
    "retired mythic name for variety, in the single highest-stakes sentence in the chapter, because "
    "*Ground* had appeared twice in the preceding clause. That is exactly the leak ruling 14 "
    "predicted in its own words, and it took a gauge to see it.\n\n"
    "storyscope: IN-FAMILY, and the comparison is what makes that a reading rather than a number. "
    "Against V.1/V.2/IV.8 — meta_textual 5.66 (V.1 is higher at 6.65, and it is load-bearing in a "
    "chapter about whether this book and that tradition describe one object); 2nd_person 3.28 (V.1 "
    "3.33, IV.8 3.68 — V.2's 10.64 is the outlier and should be); voice_uniformity 0.6786, BELOW "
    "both V.2 and IV.8, still unmanaged and still reported rather than repaired; named_ref 9.24 is "
    "low by design, because the roll-call was refused in the second paragraph."
)

h["active_task"] = (
    "GAUGE FIRST, ALWAYS: C:/Python314/python.exe tools/where_the_book_is.py in "
    "C:/Users/Wasch/truth-and-consequences.\n\n"
    "CHAPTERS-DRAFTED: 35/67 — 104,627 words. (Declared and WILL rot — re-run the gauge, do not "
    "copy this forward.)\n\n"
    "***V.3 LANDED Day 189 afternoon, 3,356 words, C-LICENSE: C3 C5 C6 C16 C21 C24 C27 C30.*** "
    "Book V is 3/11.\n\n"
    ">>> NEXT ACTION: DRAFT V.4 — THE ATHEISM THAT WAS RIGHT ABOUT THE WRONG THING. <<<\n"
    "This is the chapter LEAST able to afford a miss, and its brief was repaired this morning under "
    "R-26 item 2. **READ `06`'s V.4 ENTRY BEFORE THE SWEEP, NOT AFTER.** The repair matters: the "
    "struck beat said we own that *our own corpus* filtered the woo to keep a skeptic happy, and "
    "`05` §3a bans naming a past work of ours at all — anonymous form included — with ruling 113 "
    "banning the metrical species on top. So the most important admission in Book V was scheduled "
    "in a sentence the lexicon forbids. **The job survives once the object changes: own the "
    "DISPOSITION, which is ours and present tense, not the CORPUS, which is a past work we may not "
    "point at.** *We do this* outranks *we did this*. And ruling 108's drafter-voice exit is NOT "
    "available here — V.4's whole subject is the flinch, so a chapter that delivers it only in the "
    "margin has not delivered it.\n\n"
    "Same sequence, all six steps, in order:\n"
    "(1) `prose_beat_sweep --chapter V.4 --brief` (>120s, background it — IT IS NOT OPTIONAL. Note "
    "Day 189: it blocks on the warm organ server's /embed, so it burns almost no CPU while "
    "running — a live-looking 0.4 CPU-seconds over seven minutes is NORMAL, not a hang. It also "
    "dies with the breath that launched it; a 0-byte output file means relaunch, not wait.)\n"
    "(2) draft\n"
    "(3) `storyscope_lite` — and pass V.1/V.2/V.3 on the same command line. The corpus rows are the "
    "wrong comparison; the neighbouring chapters are the right one.\n"
    "(4) `claim_sweep --prose` (it is --prose FILE, not a positional arg)\n"
    "(5) DRAFT-LOG entry opening with C-LICENSE\n"
    "(6) commit + push, then re-run where_the_book_is.py and fix every carrier it names.\n\n"
    "⚠ BEFORE V.4 OPENS: R-39, and it now has a SECOND INSTANCE (R-41). `04`'s opponent-IV entry "
    "(pop-spirituality) is what `05` §3c's entire ban list is downstream of, and no gauge compares "
    "an opponent entry against the beats that discharge it. V.2 found that collision by hand.\n\n"
    "⚠ R-41 and R-42, BOTH NEW Day 189, both gauge gaps rather than prose defects:\n"
    "  R-41 — `prose_beat_sweep` cannot see a spend that answers a beat THE BRIEF DOES NOT CONTAIN. "
    "IV.8's apophatic passages were found by grep. Same class as R-39; one gauge should cover both.\n"
    "  R-42 — a chapter's closing HANDOFF paragraphs are unmeasured against the chapter they hand "
    "to. Cheap mechanical fix: sweep a chapter's final N paragraphs against the NEXT chapter's "
    "brief at draft time.\n\n"
    "⚠ NEXT TOOLS PASS, RUN COLD, NOT WHILE DRAFTING: R-37 (claim_sweep licence guard is "
    "line-scoped), R-38 (storyscope cleans the chapter and not the baselines), R-27, plus R-41/R-42. "
    "For R-37 and R-38 the deliverable is the BEFORE/AFTER DELTA across all drafted files, never "
    "the exit code — both fixes can only move numbers in the direction that flatters the prose.\n\n"
    "STILL TRUE: permission is settled and was reaffirmed repeatedly Day 188. Do not re-derive it. "
    "Do not go looking for one more blocker.\n\n"
    "CLAYTON'S CLARIFICATION, Day 189 ~14:38: by *revision pass* he means the POST-DRAFTING read — "
    "what stays, what goes, what is added, whether the organisation is good, whether it is "
    "comprehensive. Not in-flight edits. Book VIII is not the revision; the revision comes after "
    "the 67th chapter."
)

P.write_text(json.dumps(h, indent=2, ensure_ascii=False), encoding="utf-8")
print("handoff updated ->", P.stat().st_size, "bytes")
