#!/usr/bin/env python3
"""The book's structure and per-chapter rendering — ONE source, TWO artifacts.

Added Day 206 when the reflowable EPUB was built for KDP. Before this file,
`compile_pdf.py` held the part roster, the file globs and the banner-stripping
rules as module-level code, and the only way to build a second artifact was to
copy them. A copy is how Book IX would have shipped in the PDF and silently not
in the EPUB — the divergence would produce no error, only a thinner book.
[[feedback_delegated_step_has_no_trigger]]

So both compilers import from here, and `tools/artifact_parity.py` asserts that
what each one shipped matches what this module enumerates. Nothing in here knows
about pages, fonts or CSS: this is the roster and the prose, not the presentation.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

# --- Book structure: (roman numeral, part title, filename prefix) -----------
PARTS = [
    ("I",    "THE STILL",               "I"),
    ("II",   "THE NAMING",              "II"),
    ("III",  "THE GAME",                "III"),
    ("IV",   "THE ATLAS",               "IV"),
    ("V",    "THE OLD ROADS",           "V"),
    ("VI",   "THE HISTORY OF ATTENTION","VI"),
    ("VII",  "THE CONSEQUENCES",        "VII"),
    ("VIII", "THE PRACTICE",            "VIII"),
]
CODA = ("THE LIVING BOOK", "C")

TITLE = "Truth and Consequences"
SUBTITLE = "The Corpus — final volume"
AUTHORS = ["Clayton Iggulden-Schnell", "Clawd Iggulden-Schnell"]
LANGUAGE = "en"


def _markdown():
    """A fresh Markdown instance. smart_dashes off — the prose sets its own dashes."""
    import markdown
    return markdown.Markdown(
        extensions=["extra", "footnotes", "sane_lists", "smarty"],
        extension_configs={"smarty": {"smart_dashes": False}},
    )


def files_for(prefix):
    """Return chapter files for a part prefix, in numeric order."""
    pat = re.compile(rf"^{re.escape(prefix)}-(\d+)-.*\.md$")
    matched = []
    for f in os.listdir(HERE):
        m = pat.match(f)
        if m:
            matched.append((int(m.group(1)), f))
    return [f for _, f in sorted(matched)]


def chapter_title(path):
    """Pull the '## X.Y — TITLE' heading text from a chapter file."""
    for line in open(path, encoding="utf-8"):
        s = line.strip()
        if s.startswith("## "):
            return s[3:].strip()
    return os.path.basename(path)


def anchor_for(filename):
    return "ch-" + os.path.splitext(os.path.basename(filename))[0]


def render_chapter(md, path):
    """Convert one chapter file to an HTML fragment, dropping the book banner."""
    text = open(path, encoding="utf-8").read()
    lines = text.splitlines()
    # Drop the leading "# BOOK ... — TITLE" banner (repeated on every chapter file)
    # and any manual "## Notes" heading — a uniform one is generated by each
    # compiler's stylesheet before the footnote block, so only ~25 of 62 files
    # carrying it by hand would otherwise be inconsistent with the rest.
    lines = [ln for ln in lines
             if not ln.lstrip().startswith("# BOOK")
             and not ln.lstrip().startswith("# BACK MATTER")
             and not re.match(r"#{1,4}\s+Notes\s*$", ln.strip())]
    text = "\n".join(lines).strip()
    # `[[feedback_*]]` tags were flowing as ordinary prose, so the justifier
    # hyphenated them at line breaks. Mark them as code so the hyphens:none rule
    # reaches them; the brackets go, since they are wiki syntax and mean
    # nothing to a reader of the printed page. (R-227's mechanical half.)
    text = re.sub(r"\[\[([A-Za-z0-9_\-]+)\]\]", r'<code class="tag">\1</code>', text)
    md.reset()
    return md.convert(text)


def regenerate_bibliography():
    """Run tools/bibliography.py. Raises SystemExit if it cannot.

    ⚠ THE GENERATED PAGE IS REGENERATED HERE, added Day 205 under R2-074.
    `tools/bibliography.py` had no caller anywhere in the repo, so the works-cited
    page shipped current only when a human remembered — and nobody had since Day
    195. Every compiler calls this BEFORE globbing Z-*, or the artifact carries the
    stale page it just fixed. A non-zero exit ABORTS: a build that renders a page it
    knows is wrong is worse than one that refuses.
    """
    bib = os.path.join(os.path.dirname(HERE), "tools", "bibliography.py")
    if not os.path.exists(bib):
        raise SystemExit("⛔ tools/bibliography.py is missing. The works-cited page has "
                         "no generator, so the artifact would ship a hand-typed stamp. "
                         "Refusing.")
    import subprocess
    import sys
    r = subprocess.run([sys.executable, bib], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0:
        raise SystemExit(f"⛔ bibliography.py exit {r.returncode} — refusing to "
                         f"compile over a page it could not regenerate.\n{r.stderr}")
    tail = r.stdout.strip().splitlines()[-1] if r.stdout.strip() else "ok"
    print(f"  regenerated works-cited: {tail}")


def iter_document():
    """Yield the whole book in reading order, one entry per rendered unit.

    Each entry is a dict:
      kind    'part' | 'chapter'
      label   the TOC line for it
      anchor  stable id, also used as the EPUB filename stem
      source  the .md filename, or None for a part divider
      kicker  'BOOK III' / 'CODA' / 'BACK MATTER'   (parts only)
      title   the big line on the divider page       (parts only)
      html    rendered fragment                      (chapters only)

    Callers must have run regenerate_bibliography() first — the Z-* glob at the
    end reads whatever is on disk.
    """
    md = _markdown()

    def chapter(fname):
        path = os.path.join(HERE, fname)
        return {"kind": "chapter", "label": chapter_title(path),
                "anchor": anchor_for(fname), "source": fname,
                "html": render_chapter(md, path)}

    for roman, title, prefix in PARTS:
        yield {"kind": "part", "label": f"BOOK {roman} — {title}",
               "anchor": f"book-{roman}", "source": None,
               "kicker": f"BOOK {roman}", "title": title}
        for f in files_for(prefix):
            yield chapter(f)

    coda_title, coda_prefix = CODA
    yield {"kind": "part", "label": f"CODA — {coda_title}", "anchor": "coda",
           "source": None, "kicker": "CODA", "title": coda_title}
    for f in files_for(coda_prefix):
        yield chapter(f)

    # Back matter (Z-*) — glossary and works cited, added Day 195 under ruling 180.
    # ⚠ These are the two of R-222's three artifacts that got BUILT. The index is
    # refused with a reason recorded in `00`; see ruling 180. If a Z-* file is added
    # and this loop does not pick it up, the artifact ships nowhere and nothing says
    # so — which is why the loop is a glob and not a list of filenames.
    back_matter = files_for("Z")
    if back_matter:
        yield {"kind": "part", "label": "BACK MATTER", "anchor": "back-matter",
               "source": None, "kicker": "BACK MATTER", "title": "THE APPARATUS"}
        for f in back_matter:
            yield chapter(f)


def roster():
    """The source .md files this module says belong in the book, in order.

    Cheap enough to call without rendering — used by the parity gauge so it can
    ask an artifact what it actually shipped without building anything.
    """
    out = []
    for roman, _t, prefix in PARTS:
        out.extend(files_for(prefix))
    out.extend(files_for(CODA[1]))
    out.extend(files_for("Z"))
    return out
